services:
  microservice:
    container_name: microservice
    build: ./microservice
    volumes:
      - ./microservice/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "3011:3011"
    working_dir: /usr/src/app
    command: bash -c "npm install --no-audit && npm run dev"
  products:
    image: node:21.7.3 
    volumes:
      - ./products/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "3013:3013"
    working_dir: /usr/src/app
    command: bash -c "npm install --no-audit && npm run dev"
  gateway:
    container_name: apigateway
    build: ./apigateway
    volumes:
      - ./apigateway/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "3010:3010"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
  markets:
    container_name: markets
    build: ./markets
    volumes:
      - ./markets/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "3012:3012"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"

networks:
  msexample:
    driver: bridge