version: '3.8'

services:
  microservice-users:
    build: ./microservice-users
    environment:
      // ...existing code...
    depends_on:
      - mysql

  microservice-timer:
    build: ./microservice-timer
    environment:
      // ...existing code...
    depends_on:
      - mysql

  microservice-statistics:
    build: ./microservice-statistics
    environment:
      // ...existing code...
    depends_on:
      - mysql

  microservice-shop:
    build: ./microservice-shop
    environment:
      // ...existing code...
    depends_on:
      - mysql

  microservice-goals-milestones:
    build: ./microservice-goals-milestones
    environment:
      // ...existing code...
    depends_on:
      - mysql

  apigateway:
    build: ./apigateway
    depends_on:
      - microservice-users
      - microservice-timer
      - microservice-statistics
      - microservice-shop
      - microservice-goals-milestones

volumes:
  mysql-data: