version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: s4VFziWxEIS5640
      MYSQL_DATABASE: douchewijzer
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  microservice:
    build: ./microservice
    environment:
      DB_USER: root
      DB_PASSWORD: s4VFziWxEIS5640
      DB_NAME: douchewijzer
    ports:
      - "3011:3011"
    depends_on:
      - mysql

  apigateway:
    build: ./apigateway
    ports:
      - "3010:3010"
    depends_on:
      - microservice

volumes:
  mysql-data: