name: Super Linter in Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Run Super Linter in Docker
        run: |
          docker pull github/super-linter:latest
          docker run -e RUN_LOCAL=true -v $(pwd):/tmp/lint github/super-linter:latest
