name: ESLint Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.11.0 # Use a version suitable for all microservices

      # Discover 'code' directories and run ESLint
      - name: Run ESLint in 'code' directories
        run: |
          # Find all 'code' directories containing package.json
          for dir in $(find . -type d -name "code" -exec test -e {}/package.json \; -print); do
            parent_dir=$(basename $(dirname $dir))
            echo "Running ESLint in $parent_dir/code"
            cd $dir
            # Install dependencies
            npm install
            # Ensure ESLint is installed
            npm install eslint --save-dev
            # Generate a default ESLint configuration if missing
            if [ ! -f .eslintrc.json ]; then
              echo '{
                "extends": "eslint:recommended",
                "env": {
                  "browser": true,
                  "es2021": true,
                  "node": true
                },
                "parserOptions": {
                  "ecmaVersion": 12,
                  "sourceType": "module"
                }
              }' > .eslintrc.json
            fi
            # Run ESLint
            npx eslint . || exit 1
            cd -
          done
