name: CI/CD Pipeline

on:
  push:
    branches:
      - release

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (for linting, testing)
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install

      - name: Run Linter
        run: npm run lint

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Compose services
        run: |
          docker-compose build

      - name: Start services for testing
        run: |
          docker-compose up -d

      - name: Run Microservice tests
        run: |
          docker-compose exec microservice npm test

      - name: Run API Gateway tests
        run: |
          docker-compose exec apigateway npm test

      - name: Run Challenges API tests
        run: |
          docker-compose exec challenges-api npm test

      - name: Run Shop API tests
        run: |
          docker-compose exec shop-api npm test

      - name: Tear down services
        run: |
          docker-compose down

      - name: Set up SonarQube Scanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
          unzip sonar-scanner-cli-4.7.0.2747-linux.zip
          export PATH=$PATH:$(pwd)/sonar-scanner-4.7.0.2747-linux/bin

      - name: Run SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=YourProjectKey \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://your-sonarqube-server \
            -Dsonar.login=$SONAR_TOKEN

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Deploy to Production
        run: |
          # Add your deployment steps here
          echo "Deploying to production..."
          # Example: Deploy to server or cloud
          # curl -X POST -H "Authorization: Bearer ${{ secrets.PRODUCTION_API_KEY }}" https://your-deploy-endpoint.com

