on:
  push:
    branches:
      - release

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (for linting, testing)
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install

      - name: Run Linter
        run: npm run lint

      - name: Run Tests with Coverage
        run: |
          npm run test:coverage
  

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build Docker Compose services
        run: |
          docker-compose build

      - name: Start services for testing
        run: |
          docker-compose up -d

      - name: Wait for SonarQube to be ready
        run: |
          echo "Waiting for SonarQube to start..."
          # Wait for SonarQube to be available
          until curl -s http://localhost:9000/api/system/health | grep -q '"status":"OK"'; do
            echo "Waiting for SonarQube to start..."
            sleep 10
          done

      - name: Run Microservice tests
        run: |
          docker-compose exec -T microservice sh -c "if [ -f apigateway.test.js ]; then npx vitest run apigateway.test.js; else echo 'Test file not found'; fi"

      - name: Run API Gateway tests
        run: |
          docker-compose exec -T apigateway sh -c "if [ -f challenges-api.test.js ]; then npx vitest run challenges-api.test.js; else echo 'Test file not found'; fi"

      - name: Run Challenges API tests
        run: |
          docker-compose exec -T challenges-api sh -c "if [ -f shop-api.test.js ]; then npx vitest run shop-api.test.js; else echo 'Test file not found'; fi"

      - name: Run Shop API tests
        run: |
          docker-compose exec -T shop-api sh -c "if [ -f shop-api.test.js ]; then npx vitest run shop-api.test.js; else echo 'Test file not found'; fi"

      - name: Tear down services
        run: |
          docker-compose down
