on:
  push:
    branches:
      - release

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (for linting, testing)
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install

      - name: Run Linter
        run: npm run lint

      - name: Run Tests with Coverage
        run: |
          npm run test:coverage

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build Docker Compose services
        run: |
          docker-compose build

      - name: Start services for testing
        run: |
          docker-compose up -d

      - name: Run Tests for All Services
        run: |
          services=("microservice" "apigateway" "challenges-api" "shop-api")
          for service in "${services[@]}"; do
            test_file="test/alltests/${service}.test.js"
            docker-compose exec -T "$service" sh -c "if [ -f $test_file ]; then npx vitest $test_file; else echo 'Test file $test_file not found'; fi"
          done

      - name: Notify failure
        if: failure()
        run: |
          echo "Build failed!"

      - name: Tear down services
        run: |
          docker-compose down
